version: 1.0.0.{build}

environment:
  packageVersion: 1.0.0-alpha1

image: Visual Studio 2017

init:
  - ps: nuget.exe sources add -name aspnetvnext -source https://www.myget.org/F/aspnetvnext/api/v2
  - ps: $env:nugetVersion = "$env:packageVersion-ci-$env:appveyor_build_number"
  - ps: Write-Host "nugetVersion:" $env:nugetVersion

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '$(nugetVersion)'

before_build:
  - ps: nuget restore

build:
  verbosity: minimal

test_script:
  - ps: dotnet test test\R4Mvc.Test\R4Mvc.Test.csproj    

after_test:
  - ps: msbuild src\R4Mvc /t:pack /p:PackageVersion=$env:nugetVersion

artifacts:
  - path: '**\*.nupkg'
